apiVersion: apps/v1
kind: Deployment
metadata:
  name: dart-deployment
  labels:
    app: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: dart_backend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          env:
            - name: SERVER
              value: "13233423223"
          workingDir: /app