apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    service: backend
spec:
  selector:
    app: backend
  type: NodePort
  ports:
    - targetPort: 3000
      port: 8081
      nodePort: 30000 